#!/usr/bin/env bash
# Build the presentation assets from source:
#   1. the standalone TikZ diagrams  (diagrams/*.tex  -> diagrams/*.pdf)
#   2. the mechanisms deck           (mechanisms.tex  -> mechanisms.pdf)
# Requires: TeX Live (pdflatex + latexmk). The deck also embeds the committed
# golden figures from ../results/figures/*.png (regenerated by the model, not here).
set -euo pipefail
cd "$(dirname "$0")"

DIAGRAMS=(architecture loop channels)

echo "==> 1/2  diagrams"
pushd diagrams >/dev/null
for f in "${DIAGRAMS[@]}"; do
  printf '   - %-14s' "$f"
  latexmk -pdf -interaction=nonstopmode -halt-on-error "$f.tex" >/dev/null 2>&1 \
    && echo "ok" || { echo "FAILED — see diagrams/$f.log"; exit 1; }
done
latexmk -c >/dev/null 2>&1 || true   # drop aux, keep the PDFs
popd >/dev/null

echo "==> 2/2  deck"
latexmk -pdf -interaction=nonstopmode -halt-on-error mechanisms.tex >/dev/null 2>&1 \
  && echo "   - mechanisms.pdf ok" || { echo "   deck FAILED — see mechanisms.log"; exit 1; }
latexmk -c >/dev/null 2>&1 || true

echo ""
echo "Done."
echo "  diagrams : $(printf '%s ' "${DIAGRAMS[@]/%/.pdf}")(in diagrams/)"
echo "  deck     : mechanisms.pdf"
